package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/disp911/spacex-ui/v2/database"
	"github.com/disp911/spacex-ui/v2/database/model"
	"github.com/disp911/spacex-ui/v2/logger"
	"github.com/disp911/spacex-ui/v2/telemt"
	"github.com/disp911/spacex-ui/v2/util/json_util"
	"github.com/disp911/spacex-ui/v2/xray"
)

var (
	// telemtManager is created on first use, after the panel has loaded the
	// environment that decides where the bin folder is.
	telemtManager = sync.OnceValue(func() *telemt.Manager {
		m := telemt.NewManager()
		m.OnLog = logTelemtLine
		return m
	})

	telemtState struct {
		sync.Mutex
		online    []string
		lastError map[int]string
		// relayWarning holds, per inbound, the last word on its Xray relay.
		relayWarning map[int]string
	}
)

// TelemtService runs the telemt proxies behind mtproto inbounds and feeds
// their traffic into the same client statistics Xray inbounds use.
type TelemtService struct {
	inboundService InboundService
	settingService SettingService
}

// mtprotoSettings is the settings JSON of an mtproto inbound.
type mtprotoSettings struct {
	TlsDomain string `json:"tlsDomain"`
	// OutboundTag names the Xray outbound telemt reaches Telegram through;
	// empty connects to Telegram directly.
	OutboundTag string `json:"outboundTag,omitempty"`
	// XrayRelay is generated by the panel, never by the form; see
	// prepareMTProtoRelay.
	XrayRelay *mtprotoRelay  `json:"xrayRelay,omitempty"`
	Clients   []model.Client `json:"clients"`
}

// mtprotoRelay is the loopback SOCKS5 inbound of Xray that carries an
// mtproto inbound's traffic to the chosen outbound. The credentials keep
// other processes on the server from using it as an open proxy.
type mtprotoRelay struct {
	Port int    `json:"port"`
	User string `json:"user"`
	Pass string `json:"pass"`
}

func (r *mtprotoRelay) valid() bool {
	return r != nil && r.Port > 0 && r.Port <= 65535 && r.User != "" && r.Pass != ""
}

// mtprotoRelayTag is the Xray tag of an inbound's relay.
func mtprotoRelayTag(inboundID int) string {
	return fmt.Sprintf("mtproto-relay-%d", inboundID)
}

// mtprotoRelayKey identifies the relay an enabled mtproto inbound asks Xray
// for; it is empty when there is none and changes whenever Xray's config
// has to.
func mtprotoRelayKey(inbound *model.Inbound) string {
	if inbound == nil || inbound.Protocol != model.MTProto || !inbound.Enable {
		return ""
	}
	var s mtprotoSettings
	if json.Unmarshal([]byte(inbound.Settings), &s) != nil || s.OutboundTag == "" || !s.XrayRelay.valid() {
		return ""
	}
	return fmt.Sprintf("%s|%d|%s|%s", s.OutboundTag, s.XrayRelay.Port, s.XrayRelay.User, s.XrayRelay.Pass)
}

// prepareMTProtoRelay gives an mtproto inbound that routes through Xray its
// relay, and removes it from one that does not. The form never carries the
// relay, so an existing one is taken from the stored settings: keeping its
// port and credentials spares Xray and telemt a restart on every save. A new
// relay avoids the ports in taken, which holds the ports of the other
// inbounds and relays: one that is disabled now does not hold its port yet.
func prepareMTProtoRelay(inbound *model.Inbound, storedSettings string, taken map[int]bool) error {
	if inbound.Protocol != model.MTProto {
		return nil
	}
	settings := map[string]any{}
	if err := json.Unmarshal([]byte(inbound.Settings), &settings); err != nil {
		return err
	}
	tag, _ := settings["outboundTag"].(string)
	tag = strings.TrimSpace(tag)
	if tag == "" {
		delete(settings, "outboundTag")
		delete(settings, "xrayRelay")
	} else {
		settings["outboundTag"] = tag
		var stored mtprotoSettings
		_ = json.Unmarshal([]byte(storedSettings), &stored)
		relay := stored.XrayRelay
		if !relay.valid() {
			port, err := freeRelayPort(taken)
			if err != nil {
				return err
			}
			user, err := telemt.RandomHex(8)
			if err != nil {
				return err
			}
			pass, err := telemt.RandomHex(16)
			if err != nil {
				return err
			}
			relay = &mtprotoRelay{Port: port, User: user, Pass: pass}
		}
		settings["xrayRelay"] = relay
	}
	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	inbound.Settings = string(data)
	return nil
}

// freeRelayPort picks an unused loopback port that is not in taken.
func freeRelayPort(taken map[int]bool) (int, error) {
	for range 20 {
		ports, err := telemt.FreeLoopbackPorts(1)
		if err != nil {
			return 0, err
		}
		if !taken[ports[0]] {
			return ports[0], nil
		}
	}
	return 0, errors.New("no free port for the Xray relay")
}

// portsTakenByOtherInbounds lists the ports of every inbound but one and of
// every mtproto relay but its own.
func portsTakenByOtherInbounds(exceptID int) (map[int]bool, error) {
	var inbounds []*model.Inbound
	if err := database.GetDB().Model(model.Inbound{}).Select("id, port, protocol, settings").Find(&inbounds).Error; err != nil {
		return nil, err
	}
	taken := make(map[int]bool, len(inbounds))
	for _, inbound := range inbounds {
		if inbound.Id == exceptID {
			continue
		}
		taken[inbound.Port] = true
		if inbound.Protocol == model.MTProto {
			var s mtprotoSettings
			if json.Unmarshal([]byte(inbound.Settings), &s) == nil && s.XrayRelay.valid() {
				taken[s.XrayRelay.Port] = true
			}
		}
	}
	return taken, nil
}

// mtprotoRelayUsesPort reports whether the relay of an mtproto inbound other
// than ignoreID holds port.
func mtprotoRelayUsesPort(port, ignoreID int) (bool, error) {
	var inbounds []*model.Inbound
	if err := database.GetDB().Model(model.Inbound{}).Select("id, settings").
		Where("protocol = ? AND id != ?", model.MTProto, ignoreID).Find(&inbounds).Error; err != nil {
		return false, err
	}
	for _, inbound := range inbounds {
		var s mtprotoSettings
		if json.Unmarshal([]byte(inbound.Settings), &s) == nil && s.XrayRelay.valid() && s.XrayRelay.Port == port {
			return true, nil
		}
	}
	return false, nil
}

// xrayOutboundTags returns the tags of the outbounds in an Xray config or
// template, mapped to their protocols.
func xrayOutboundTags(outbounds []byte) map[string]string {
	var list []struct {
		Tag      string `json:"tag"`
		Protocol string `json:"protocol"`
	}
	_ = json.Unmarshal(outbounds, &list)
	tags := make(map[string]string, len(list))
	for _, o := range list {
		if o.Tag != "" {
			tags[o.Tag] = o.Protocol
		}
	}
	return tags
}

// mtprotoRelayFor returns the relay of an mtproto inbound and the outbound it
// leads to, or nil when the inbound connects directly. An outbound that has
// since been removed from Xray's config falls back to a direct connection,
// so Xray and telemt always agree on whether the relay exists.
func mtprotoRelayFor(s mtprotoSettings, outbounds map[string]string) (*mtprotoRelay, string) {
	if s.OutboundTag == "" || !s.XrayRelay.valid() {
		return nil, ""
	}
	if _, ok := outbounds[s.OutboundTag]; !ok {
		return nil, ""
	}
	return s.XrayRelay, s.OutboundTag
}

// XrayOutboundTags lists the outbounds of the Xray template an mtproto
// inbound may route through: every one with a tag except blackholes.
func (s *TelemtService) XrayOutboundTags() ([]string, error) {
	template, err := s.settingService.GetXrayConfigTemplate()
	if err != nil {
		return nil, err
	}
	var cfg struct {
		Outbounds json.RawMessage `json:"outbounds"`
	}
	if err := json.Unmarshal([]byte(template), &cfg); err != nil {
		return nil, err
	}
	var tags []string
	for tag, protocol := range xrayOutboundTags(cfg.Outbounds) {
		if protocol != "blackhole" {
			tags = append(tags, tag)
		}
	}
	sort.Strings(tags)
	return tags, nil
}

// validateMTProtoInbound checks an mtproto inbound before it is saved; other
// protocols pass unchanged.
func validateMTProtoInbound(inbound *model.Inbound, clients []model.Client) error {
	if inbound.Protocol != model.MTProto {
		return nil
	}
	if !telemt.IsInstalled() {
		return errors.New("mtproto is not available: this build has no telemt binary for this platform")
	}
	var settings mtprotoSettings
	if err := json.Unmarshal([]byte(inbound.Settings), &settings); err != nil {
		return err
	}
	if !telemt.ValidTLSDomain(settings.TlsDomain) {
		return fmt.Errorf("invalid masking domain %q", settings.TlsDomain)
	}
	if inbound.Listen != "" && net.ParseIP(inbound.Listen) == nil {
		return fmt.Errorf("mtproto listen address must be an IP, got %q", inbound.Listen)
	}
	return validateMTProtoClients(inbound.Protocol, clients)
}

// validateMTProtoClients checks the secrets of clients of an mtproto inbound.
func validateMTProtoClients(protocol model.Protocol, clients []model.Client) error {
	if protocol != model.MTProto {
		return nil
	}
	for _, c := range clients {
		if !telemt.ValidSecret(c.ID) {
			return fmt.Errorf("client %q: secret must be 32 lowercase hex characters", c.Email)
		}
	}
	return nil
}

// desiredInstances builds the telemt instances every enabled mtproto inbound
// should run. Clients that are disabled or depleted are kept, marked
// disabled, so telemt cuts the sessions they still have open.
func (s *TelemtService) desiredInstances() ([]telemt.Instance, error) {
	db := database.GetDB()
	var inbounds []*model.Inbound
	if err := db.Model(model.Inbound{}).Where("protocol = ? AND enable = ?", model.MTProto, true).Find(&inbounds).Error; err != nil {
		return nil, err
	}
	var outbounds map[string]string
	if template, err := s.settingService.GetXrayConfigTemplate(); err == nil {
		var cfg struct {
			Outbounds json.RawMessage `json:"outbounds"`
		}
		if json.Unmarshal([]byte(template), &cfg) == nil {
			outbounds = xrayOutboundTags(cfg.Outbounds)
		}
	}
	instances := make([]telemt.Instance, 0, len(inbounds))
	for _, inbound := range inbounds {
		var settings mtprotoSettings
		if err := json.Unmarshal([]byte(inbound.Settings), &settings); err != nil {
			logger.Warning("telemt: bad settings of inbound", inbound.Id, err)
			continue
		}
		var traffics []xray.ClientTraffic
		if err := db.Model(xray.ClientTraffic{}).Select("email, enable").Where("inbound_id = ?", inbound.Id).Find(&traffics).Error; err != nil {
			return nil, err
		}
		depleted := make(map[string]bool, len(traffics))
		for _, t := range traffics {
			if !t.Enable {
				depleted[t.Email] = true
			}
		}

		inst := telemt.Instance{
			InboundID: inbound.Id,
			Tag:       inbound.Tag,
			Listen:    inbound.Listen,
			Port:      inbound.Port,
			TLSDomain: settings.TlsDomain,
			Emails:    map[string]string{},
		}
		if relay, _ := mtprotoRelayFor(settings, outbounds); relay != nil {
			inst.Upstream = &telemt.Upstream{
				Address:  fmt.Sprintf("127.0.0.1:%d", relay.Port),
				Username: relay.User,
				Password: relay.Pass,
			}
		}
		relayWarning := ""
		if settings.OutboundTag != "" && inst.Upstream == nil {
			relayWarning = fmt.Sprintf("Xray outbound %q no longer exists; connecting to Telegram directly", settings.OutboundTag)
		}
		reportRelayWarning(inbound.Id, relayWarning)
		for _, c := range settings.Clients {
			if c.Email == "" || !telemt.ValidSecret(c.ID) {
				continue
			}
			name := telemt.UserName(c.Email)
			if _, dup := inst.Emails[name]; dup {
				continue
			}
			inst.Emails[name] = c.Email
			inst.Users = append(inst.Users, mtprotoUser(name, c, !c.Enable || depleted[c.Email]))
		}
		instances = append(instances, inst)
	}
	return instances, nil
}

// mtprotoUser maps a panel client to its telemt account. Rates are entered
// in Mbit/s. An expiry counted from the first connection is still negative
// and stays with the panel; telemt only gets a fixed date.
func mtprotoUser(name string, c model.Client, disabled bool) telemt.User {
	u := telemt.User{
		Name:         name,
		Secret:       c.ID,
		Disabled:     disabled,
		MaxUniqueIPs: c.LimitIP,
		MaxTCPConns:  max(c.MaxConns, 0),
		RateUpBps:    uint64(max(c.RateUp, 0)) * 1_000_000,
		RateDownBps:  uint64(max(c.RateDown, 0)) * 1_000_000,
	}
	if c.ExpiryTime > 0 {
		u.Expires = time.UnixMilli(c.ExpiryTime)
	}
	return u
}

// Sync starts, reloads, restarts or stops telemt processes to match the
// mtproto inbounds in the database. It is cheap when nothing changed.
func (s *TelemtService) Sync() {
	want, err := s.desiredInstances()
	if err != nil {
		logger.Warning("telemt: load mtproto inbounds:", err)
		return
	}
	m := telemtManager()
	if !m.Installed() {
		if len(want) > 0 {
			reportTelemtError(0, "telemt binary is missing; mtproto inbounds cannot run on this platform")
		}
		return
	}
	_ = m.Sync(want)
	for _, w := range want {
		reportTelemtError(w.InboundID, m.LastError(w.InboundID))
	}
}

// reportRelayWarning logs a relay warning once per change, not on every sync.
func reportRelayWarning(inboundID int, msg string) {
	telemtState.Lock()
	defer telemtState.Unlock()
	if telemtState.relayWarning == nil {
		telemtState.relayWarning = map[int]string{}
	}
	if telemtState.relayWarning[inboundID] == msg {
		return
	}
	telemtState.relayWarning[inboundID] = msg
	if msg != "" {
		logger.Warningf("telemt (inbound %d): %s", inboundID, msg)
	}
}

// reportTelemtError logs a telemt error once per change, not on every sync.
func reportTelemtError(inboundID int, msg string) {
	telemtState.Lock()
	defer telemtState.Unlock()
	if telemtState.lastError == nil {
		telemtState.lastError = map[int]string{}
	}
	if telemtState.lastError[inboundID] == msg {
		return
	}
	telemtState.lastError[inboundID] = msg
	if msg != "" {
		logger.Warningf("telemt (inbound %d): %s", inboundID, msg)
	}
}

// CollectTraffic records the traffic of all telemt processes since the last
// call, then re-syncs if a client ran out of quota or time.
func (s *TelemtService) CollectTraffic() {
	traffics := telemtManager().CollectTraffic(context.Background())
	var inboundTraffics []*xray.Traffic
	var clientTraffics []*xray.ClientTraffic
	online := make([]string, 0)
	for _, it := range traffics {
		if it.Up+it.Down > 0 {
			inboundTraffics = append(inboundTraffics, &xray.Traffic{IsInbound: true, Tag: it.Tag, Up: it.Up, Down: it.Down})
		}
		for _, c := range it.Clients {
			if c.Online {
				online = append(online, c.Email)
			}
			if c.Up+c.Down > 0 {
				clientTraffics = append(clientTraffics, &xray.ClientTraffic{Email: c.Email, Up: c.Up, Down: c.Down})
			}
		}
	}
	telemtState.Lock()
	telemtState.online = online
	telemtState.Unlock()

	if len(clientTraffics) == 0 && len(inboundTraffics) == 0 {
		return
	}
	_, clientsDisabled, err := s.inboundService.AddTelemtTraffic(inboundTraffics, clientTraffics)
	if err != nil {
		logger.Warning("telemt: add traffic:", err)
	}
	if clientsDisabled {
		s.Sync()
	}
}

// OnlineClients returns the emails of clients with a live telemt connection.
func (s *TelemtService) OnlineClients() []string {
	telemtState.Lock()
	defer telemtState.Unlock()
	return append([]string(nil), telemtState.online...)
}

// StopAll stops every telemt process, for panel shutdown.
func (s *TelemtService) StopAll() {
	telemtManager().StopAll()
}

func logTelemtLine(inboundID int, line string) {
	msg := fmt.Sprintf("telemt (inbound %d): %s", inboundID, line)
	if strings.Contains(line, "ERROR") || strings.Contains(line, "WARN") {
		logger.Warning(msg)
	} else {
		logger.Debug(msg)
	}
}

// ClientIPs returns the addresses an mtproto client connects from, as its
// inbound's telemt process sees them. ok is false for a client of any other
// protocol, whose addresses the panel logs itself.
func (s *TelemtService) ClientIPs(email string) (ips telemt.UserIPs, ok bool, err error) {
	db := database.GetDB()
	var inbound model.Inbound
	err = db.Model(model.Inbound{}).
		Joins("JOIN client_traffics ON client_traffics.inbound_id = inbounds.id").
		Where("client_traffics.email = ?", email).
		First(&inbound).Error
	if err != nil || inbound.Protocol != model.MTProto {
		return telemt.UserIPs{}, false, nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	ips, err = telemtManager().UserIPs(ctx, inbound.Id, telemt.UserName(email))
	return ips, true, err
}

// addMTProtoRelays gives every enabled mtproto inbound that routes through
// Xray its loopback SOCKS5 inbound, and a routing rule ahead of all others
// that sends that inbound to the chosen outbound, so no rule of the user's
// can catch the traffic first.
func addMTProtoRelays(cfg *xray.Config, inbounds []*model.Inbound) error {
	outbounds := xrayOutboundTags(cfg.OutboundConfigs)
	var rules []any
	for _, inbound := range inbounds {
		if !inbound.Enable || inbound.Protocol != model.MTProto {
			continue
		}
		var settings mtprotoSettings
		if json.Unmarshal([]byte(inbound.Settings), &settings) != nil {
			continue
		}
		relay, outboundTag := mtprotoRelayFor(settings, outbounds)
		if relay == nil {
			continue
		}
		socks, err := json.Marshal(map[string]any{
			"auth":     "password",
			"accounts": []map[string]string{{"user": relay.User, "pass": relay.Pass}},
			"udp":      false,
		})
		if err != nil {
			return err
		}
		tag := mtprotoRelayTag(inbound.Id)
		cfg.InboundConfigs = append(cfg.InboundConfigs, xray.InboundConfig{
			Listen:   json_util.RawMessage(`"127.0.0.1"`),
			Port:     relay.Port,
			Protocol: "socks",
			Settings: socks,
			Tag:      tag,
		})
		rules = append(rules, map[string]any{"type": "field", "inboundTag": []string{tag}, "outboundTag": outboundTag})
	}
	if len(rules) == 0 {
		return nil
	}
	routing := map[string]any{}
	if len(cfg.RouterConfig) > 0 {
		if err := json.Unmarshal(cfg.RouterConfig, &routing); err != nil {
			return err
		}
	}
	existing, _ := routing["rules"].([]any)
	routing["rules"] = append(rules, existing...)
	data, err := json.Marshal(routing)
	if err != nil {
		return err
	}
	cfg.RouterConfig = data
	return nil
}
