package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"strings"
	"sync"
	"time"

	"github.com/disp911/spacex-ui/v2/database"
	"github.com/disp911/spacex-ui/v2/database/model"
	"github.com/disp911/spacex-ui/v2/logger"
	"github.com/disp911/spacex-ui/v2/telemt"
	"github.com/disp911/spacex-ui/v2/xray"
)

var (
	// telemtManager is created on first use, after the panel has loaded the
	// environment that decides where the bin folder is.
	telemtManager = sync.OnceValue(func() *telemt.Manager {
		m := telemt.NewManager()
		m.OnLog = logTelemtLine
		return m
	})

	telemtState struct {
		sync.Mutex
		online    []string
		lastError map[int]string
		// webWarning holds, per inbound, the last word on its WEB proxy.
		webWarning map[int]string
	}

	// telemtWebFront is what the panel's web server tells the service about
	// serving WEB proxies; see SetTelemtWebFront.
	telemtWebFront struct {
		sync.Mutex
		decoyPort int
		ready     bool
	}
)

// SetTelemtWebFront records whether the panel serves HTTPS on port 443, which
// a WEB proxy needs as its front, and the loopback port of the decoy site
// telemt sends uncredentialed WEB requests to; 0 when there is none.
func SetTelemtWebFront(decoyPort int, httpsOn443 bool) {
	telemtWebFront.Lock()
	defer telemtWebFront.Unlock()
	telemtWebFront.decoyPort = decoyPort
	telemtWebFront.ready = httpsOn443 && decoyPort > 0
}

// TelemtWebRoute returns the loopback port of the running WEB proxy whose
// secret path is basePath.
func TelemtWebRoute(basePath string) (int, bool) {
	return telemtManager().WebRoute(basePath)
}

// TelemtService runs the telemt proxies behind mtproto inbounds and feeds
// their traffic into the same client statistics Xray inbounds use.
type TelemtService struct {
	inboundService InboundService
}

// mtprotoSettings is the settings JSON of an mtproto inbound.
type mtprotoSettings struct {
	TlsDomain string `json:"tlsDomain"`
	// Web is the Telegram WEB proxy of the inbound; see prepareMTProtoWeb.
	Web     *mtprotoWeb    `json:"web,omitempty"`
	Clients []model.Client `json:"clients"`
}

// mtprotoWeb serves an mtproto inbound's clients as a Telegram WEB proxy at
// https://Host/Path/, behind the panel's own HTTPS listener on port 443.
type mtprotoWeb struct {
	Enable bool   `json:"enable"`
	Host   string `json:"host"`
	// Path is the secret first segment of the URL, generated by the panel.
	Path string `json:"path"`
	// PublicIP is the address Host resolves to, looked up on save unless
	// the admin entered one.
	PublicIP string `json:"publicIp"`
}

func (w *mtprotoWeb) on() bool {
	return w != nil && w.Enable
}

// prepareMTProtoWeb completes the WEB proxy of an mtproto inbound before it
// is saved: it normalises the host, gives the inbound a path of its own
// unless it keeps a valid one no other inbound uses (a cloned inbound brings
// its original's), and looks up the public IP the host resolves to unless
// one was entered. The settings of an inbound without WEB are left alone, so
// turning it back on keeps the old link.
//
// usedPaths holds the paths of the other inbounds; lookup resolves a host.
func prepareMTProtoWeb(inbound *model.Inbound, usedPaths map[string]bool, lookup func(host string) (string, error)) error {
	if inbound.Protocol != model.MTProto {
		return nil
	}
	settings := map[string]any{}
	if err := json.Unmarshal([]byte(inbound.Settings), &settings); err != nil {
		return err
	}
	raw, ok := settings["web"]
	if !ok {
		return nil
	}
	data, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	var web mtprotoWeb
	if err := json.Unmarshal(data, &web); err != nil {
		return err
	}
	if !web.Enable {
		return nil
	}
	web.Host = strings.ToLower(strings.TrimSuffix(strings.TrimSpace(web.Host), "."))
	if !telemt.ValidWebHost(web.Host) {
		return fmt.Errorf("WEB proxy: %q is not a domain name", web.Host)
	}
	if !telemt.ValidWebBasePath(web.Path) || usedPaths[web.Path] {
		if web.Path, err = telemt.RandomHex(12); err != nil {
			return err
		}
	}
	web.PublicIP = strings.TrimSpace(web.PublicIP)
	if web.PublicIP == "" {
		if web.PublicIP, err = lookup(web.Host); err != nil {
			return err
		}
	}
	settings["web"] = web
	if data, err = json.MarshalIndent(settings, "", "  "); err != nil {
		return err
	}
	inbound.Settings = string(data)
	return nil
}

// lookupPublicIP resolves host, preferring an IPv4 address.
func lookupPublicIP(host string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	addrs, err := net.DefaultResolver.LookupIPAddr(ctx, host)
	if err != nil || len(addrs) == 0 {
		return "", fmt.Errorf("WEB proxy: cannot resolve %s; enter the server IP by hand", host)
	}
	for _, a := range addrs {
		if ip4 := a.IP.To4(); ip4 != nil {
			return ip4.String(), nil
		}
	}
	return addrs[0].IP.String(), nil
}

// errSecondMTProtoInbound refuses a second mtproto inbound: the panel runs
// one telemt process, for a single mtproto inbound.
var errSecondMTProtoInbound = errors.New("only one mtproto inbound is allowed")

// checkSingleMTProtoInbound fails when an mtproto inbound other than the one
// with id exceptID exists; 0 checks for any.
func checkSingleMTProtoInbound(exceptID int) error {
	var count int64
	err := database.GetDB().Model(model.Inbound{}).
		Where("protocol = ? AND id <> ?", model.MTProto, exceptID).
		Count(&count).Error
	if err != nil {
		return err
	}
	if count > 0 {
		return errSecondMTProtoInbound
	}
	return nil
}

// webPathsOfOtherInbounds lists the WEB paths of every mtproto inbound but
// one.
func webPathsOfOtherInbounds(exceptID int) (map[string]bool, error) {
	var inbounds []*model.Inbound
	if err := database.GetDB().Model(model.Inbound{}).Select("id, settings").
		Where("protocol = ? AND id != ?", model.MTProto, exceptID).Find(&inbounds).Error; err != nil {
		return nil, err
	}
	paths := map[string]bool{}
	for _, inbound := range inbounds {
		var s mtprotoSettings
		if json.Unmarshal([]byte(inbound.Settings), &s) == nil && s.Web != nil && s.Web.Path != "" {
			paths[s.Web.Path] = true
		}
	}
	return paths, nil
}

// validateMTProtoInbound checks an mtproto inbound before it is saved; other
// protocols pass unchanged.
func validateMTProtoInbound(inbound *model.Inbound, clients []model.Client) error {
	if inbound.Protocol != model.MTProto {
		return nil
	}
	if !telemt.IsInstalled() {
		return errors.New("mtproto is not available: this build has no telemt binary for this platform")
	}
	var settings mtprotoSettings
	if err := json.Unmarshal([]byte(inbound.Settings), &settings); err != nil {
		return err
	}
	if !telemt.ValidTLSDomain(settings.TlsDomain) {
		return fmt.Errorf("invalid masking domain %q", settings.TlsDomain)
	}
	if inbound.Listen != "" && net.ParseIP(inbound.Listen) == nil {
		return fmt.Errorf("mtproto listen address must be an IP, got %q", inbound.Listen)
	}
	if w := settings.Web; w.on() {
		if !telemt.ValidWebHost(w.Host) || !telemt.ValidWebBasePath(w.Path) {
			return fmt.Errorf("WEB proxy: %q is not a domain name", w.Host)
		}
		if ip := net.ParseIP(w.PublicIP); ip == nil || ip.IsUnspecified() {
			return fmt.Errorf("WEB proxy: %q is not an IP address", w.PublicIP)
		}
	}
	return validateMTProtoClients(inbound.Protocol, clients)
}

// validateMTProtoClients checks the secrets of clients of an mtproto inbound.
func validateMTProtoClients(protocol model.Protocol, clients []model.Client) error {
	if protocol != model.MTProto {
		return nil
	}
	for _, c := range clients {
		if !telemt.ValidSecret(c.ID) {
			return fmt.Errorf("client %q: secret must be 32 lowercase hex characters", c.Email)
		}
	}
	return nil
}

// desiredInstances builds the telemt instances every enabled mtproto inbound
// should run. Clients that are disabled or depleted are kept, marked
// disabled, so telemt cuts the sessions they still have open.
func (s *TelemtService) desiredInstances() ([]telemt.Instance, error) {
	db := database.GetDB()
	var inbounds []*model.Inbound
	if err := db.Model(model.Inbound{}).Where("protocol = ? AND enable = ?", model.MTProto, true).Find(&inbounds).Error; err != nil {
		return nil, err
	}
	instances := make([]telemt.Instance, 0, len(inbounds))
	for _, inbound := range inbounds {
		var settings mtprotoSettings
		if err := json.Unmarshal([]byte(inbound.Settings), &settings); err != nil {
			logger.Warning("telemt: bad settings of inbound", inbound.Id, err)
			continue
		}
		var traffics []xray.ClientTraffic
		if err := db.Model(xray.ClientTraffic{}).Select("email, enable").Where("inbound_id = ?", inbound.Id).Find(&traffics).Error; err != nil {
			return nil, err
		}
		depleted := make(map[string]bool, len(traffics))
		for _, t := range traffics {
			if !t.Enable {
				depleted[t.Email] = true
			}
		}

		inst := telemt.Instance{
			InboundID: inbound.Id,
			Tag:       inbound.Tag,
			Listen:    inbound.Listen,
			Port:      inbound.Port,
			TLSDomain: settings.TlsDomain,
			Emails:    map[string]string{},
		}
		webWarning := ""
		if w := settings.Web; w.on() {
			if web, ok := telemtWebInstance(w); ok {
				inst.Web = web
			} else {
				webWarning = "the WEB proxy is off: it needs the panel itself to serve HTTPS on port 443"
			}
		}
		reportWebWarning(inbound.Id, webWarning)
		for _, c := range settings.Clients {
			if c.Email == "" || !telemt.ValidSecret(c.ID) {
				continue
			}
			name := telemt.UserName(c.Email)
			if _, dup := inst.Emails[name]; dup {
				continue
			}
			inst.Emails[name] = c.Email
			inst.Users = append(inst.Users, mtprotoUser(name, c, !c.Enable || depleted[c.Email]))
		}
		instances = append(instances, inst)
	}
	return instances, nil
}

// telemtWebInstance returns the WEB proxy of an inbound, or false while the
// panel cannot be its front.
func telemtWebInstance(w *mtprotoWeb) (*telemt.WebInstance, bool) {
	telemtWebFront.Lock()
	defer telemtWebFront.Unlock()
	if !telemtWebFront.ready {
		return nil, false
	}
	return &telemt.WebInstance{Host: w.Host, BasePath: w.Path, PublicIP: w.PublicIP, DecoyPort: telemtWebFront.decoyPort}, true
}

// mtprotoUser maps a panel client to its telemt account. Rates are entered
// in Mbit/s. An expiry counted from the first connection is still negative
// and stays with the panel; telemt only gets a fixed date.
func mtprotoUser(name string, c model.Client, disabled bool) telemt.User {
	u := telemt.User{
		Name:         name,
		Secret:       c.ID,
		Disabled:     disabled,
		MaxUniqueIPs: c.LimitIP,
		MaxTCPConns:  max(c.MaxConns, 0),
		RateUpBps:    mbitToBps(c.RateUp),
		RateDownBps:  mbitToBps(c.RateDown),
	}
	if c.ExpiryTime > 0 {
		u.Expires = time.UnixMilli(c.ExpiryTime)
	}
	return u
}

// mbitToBps converts a rate in Mbit/s, capping it at the highest rate telemt
// accepts so one oversized client cannot break the whole inbound's config.
func mbitToBps(mbit int) uint64 {
	const maxMbit = telemt.MaxRateBps / 1_000_000
	return uint64(min(max(mbit, 0), maxMbit)) * 1_000_000
}

// Sync starts, reloads, restarts or stops telemt processes to match the
// mtproto inbounds in the database. It is cheap when nothing changed.
func (s *TelemtService) Sync() {
	want, err := s.desiredInstances()
	if err != nil {
		logger.Warning("telemt: load mtproto inbounds:", err)
		return
	}
	m := telemtManager()
	if !m.Installed() {
		if len(want) > 0 {
			reportTelemtError(0, "telemt binary is missing; mtproto inbounds cannot run on this platform")
		}
		return
	}
	_ = m.Sync(want)
	for _, w := range want {
		reportTelemtError(w.InboundID, m.LastError(w.InboundID))
	}
}

// reportWebWarning logs a WEB proxy warning once per change.
func reportWebWarning(inboundID int, msg string) {
	telemtState.Lock()
	defer telemtState.Unlock()
	if telemtState.webWarning == nil {
		telemtState.webWarning = map[int]string{}
	}
	if telemtState.webWarning[inboundID] == msg {
		return
	}
	telemtState.webWarning[inboundID] = msg
	if msg != "" {
		logger.Warningf("telemt (inbound %d): %s", inboundID, msg)
	}
}

// reportTelemtError logs a telemt error once per change, not on every sync.
func reportTelemtError(inboundID int, msg string) {
	telemtState.Lock()
	defer telemtState.Unlock()
	if telemtState.lastError == nil {
		telemtState.lastError = map[int]string{}
	}
	if telemtState.lastError[inboundID] == msg {
		return
	}
	telemtState.lastError[inboundID] = msg
	if msg != "" {
		logger.Warningf("telemt (inbound %d): %s", inboundID, msg)
	}
}

// CollectTraffic records the traffic of all telemt processes since the last
// call, then re-syncs if a client ran out of quota or time.
func (s *TelemtService) CollectTraffic() {
	traffics := telemtManager().CollectTraffic(context.Background())
	var inboundTraffics []*xray.Traffic
	var clientTraffics []*xray.ClientTraffic
	online := make([]string, 0)
	for _, it := range traffics {
		if it.Up+it.Down > 0 {
			inboundTraffics = append(inboundTraffics, &xray.Traffic{IsInbound: true, Tag: it.Tag, Up: it.Up, Down: it.Down})
		}
		for _, c := range it.Clients {
			if c.Online {
				online = append(online, c.Email)
			}
			if c.Up+c.Down > 0 {
				clientTraffics = append(clientTraffics, &xray.ClientTraffic{Email: c.Email, Up: c.Up, Down: c.Down})
			}
		}
	}
	telemtState.Lock()
	telemtState.online = online
	telemtState.Unlock()

	if len(clientTraffics) == 0 && len(inboundTraffics) == 0 {
		return
	}
	_, clientsDisabled, err := s.inboundService.AddTelemtTraffic(inboundTraffics, clientTraffics)
	if err != nil {
		logger.Warning("telemt: add traffic:", err)
	}
	if clientsDisabled {
		s.Sync()
	}
}

// OnlineClients returns the emails of clients with a live telemt connection.
func (s *TelemtService) OnlineClients() []string {
	telemtState.Lock()
	defer telemtState.Unlock()
	return append([]string(nil), telemtState.online...)
}

// StopAll stops every telemt process, for panel shutdown.
func (s *TelemtService) StopAll() {
	telemtManager().StopAll()
}

func logTelemtLine(inboundID int, line string) {
	msg := fmt.Sprintf("telemt (inbound %d): %s", inboundID, line)
	if strings.Contains(line, "ERROR") || strings.Contains(line, "WARN") {
		logger.Warning(msg)
	} else {
		logger.Debug(msg)
	}
}

// ClientIPs returns the addresses an mtproto client connects from, as its
// inbound's telemt process sees them. ok is false for a client of any other
// protocol, whose addresses the panel logs itself.
func (s *TelemtService) ClientIPs(email string) (ips telemt.UserIPs, ok bool, err error) {
	db := database.GetDB()
	var inbound model.Inbound
	err = db.Model(model.Inbound{}).
		Joins("JOIN client_traffics ON client_traffics.inbound_id = inbounds.id").
		Where("client_traffics.email = ?", email).
		First(&inbound).Error
	if err != nil || inbound.Protocol != model.MTProto {
		return telemt.UserIPs{}, false, nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	ips, err = telemtManager().UserIPs(ctx, inbound.Id, telemt.UserName(email))
	return ips, true, err
}
