// Package telemt runs the bundled telemt MTProto proxy for Telegram. Every
// panel inbound with the mtproto protocol gets its own telemt process; the
// panel renders the inbound into telemt's TOML config and reads per-client
// traffic back from telemt's loopback metrics endpoint.
package telemt

import (
	"errors"
	"fmt"
	"net"
	"regexp"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

// Settings are the per-inbound options.
type Settings struct {
	// Listen is the IP to bind; empty binds all interfaces.
	Listen string
	// Port is the public TCP port Telegram clients connect to.
	Port int
	// TLSDomain is the real website the Fake-TLS handshake imitates. It is
	// encoded into every ee-link, so changing it invalidates issued links.
	TLSDomain string
	// MetricsPort is the loopback port of telemt's metrics endpoint.
	MetricsPort int
	// APIPort is the loopback port of telemt's control API, which the panel
	// only reads from; 0 keeps the API off.
	APIPort int
	// APIToken is the exact Authorization header the API demands.
	APIToken string
	// Upstream, when set, carries the traffic to Telegram through a SOCKS5
	// proxy instead of connecting to the data centres directly.
	Upstream *Upstream
}

// Upstream is a SOCKS5 proxy telemt reaches Telegram through.
type Upstream struct {
	// Address is host:port.
	Address  string
	Username string
	Password string
}

// User is one proxy account.
type User struct {
	// Name is the telemt user name; see UserName.
	Name   string
	Secret string
	// Disabled users stay in the config marked as such: telemt cancels the
	// live sessions of a user it sees disabled, while a user that simply
	// disappears from the config keeps the sessions already open.
	Disabled bool
	// MaxUniqueIPs caps concurrent source IPs; 0 means unlimited.
	MaxUniqueIPs int
	// MaxTCPConns caps concurrent connections; 0 means unlimited.
	MaxTCPConns int
	// RateUpBps and RateDownBps cap the client's upload and download in
	// bits per second; 0 leaves that direction unlimited.
	RateUpBps, RateDownBps uint64
	// Expires is when telemt stops accepting the user; zero never expires.
	Expires time.Time
}

var (
	userNamePattern  = regexp.MustCompile(`^[A-Za-z0-9_.-]{1,64}$`)
	secretPattern    = regexp.MustCompile(`^[0-9a-f]{32}$`)
	tlsDomainPattern = regexp.MustCompile(`^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$`)
	// The API token and the upstream credentials are generated by the
	// panel; the patterns only keep anything else out of the config file.
	apiTokenPattern   = regexp.MustCompile(`^[0-9a-f]{32,128}$`)
	credentialPattern = regexp.MustCompile(`^[A-Za-z0-9]{1,64}$`)
)

// ValidSecret reports whether secret is a 32-character lowercase hex secret.
func ValidSecret(secret string) bool {
	return secretPattern.MatchString(secret)
}

// ValidTLSDomain reports whether domain is a plain host name usable as the
// Fake-TLS domain.
func ValidTLSDomain(domain string) bool {
	return len(domain) <= 253 && tlsDomainPattern.MatchString(domain)
}

// Validate checks the settings before they are written to a config file.
func (s Settings) Validate() error {
	if s.Port < 1 || s.Port > 65535 {
		return fmt.Errorf("invalid proxy port %d", s.Port)
	}
	if !ValidTLSDomain(s.TLSDomain) {
		return fmt.Errorf("invalid TLS domain %q", s.TLSDomain)
	}
	if s.Listen != "" && net.ParseIP(s.Listen) == nil {
		return fmt.Errorf("invalid listen address %q", s.Listen)
	}
	if s.MetricsPort < 1 || s.MetricsPort > 65535 || s.MetricsPort == s.Port {
		return fmt.Errorf("invalid metrics port %d", s.MetricsPort)
	}
	if s.APIPort != 0 {
		if s.APIPort < 1 || s.APIPort > 65535 || s.APIPort == s.Port || s.APIPort == s.MetricsPort {
			return fmt.Errorf("invalid API port %d", s.APIPort)
		}
		if !apiTokenPattern.MatchString(s.APIToken) {
			return errors.New("invalid API token")
		}
	}
	if u := s.Upstream; u != nil {
		if _, port, err := net.SplitHostPort(u.Address); err != nil || port == "" {
			return fmt.Errorf("invalid upstream address %q", u.Address)
		}
		if !credentialPattern.MatchString(u.Username) || !credentialPattern.MatchString(u.Password) {
			return errors.New("invalid upstream credentials")
		}
	}
	return nil
}

type fileConfig struct {
	General    fileGeneral    `toml:"general"`
	Server     fileServer     `toml:"server"`
	Censorship fileCensorship `toml:"censorship"`
	Access     fileAccess     `toml:"access"`
	Upstreams  []fileUpstream `toml:"upstreams,omitempty"`
}

type fileGeneral struct {
	LogLevel       string    `toml:"log_level"`
	DisableColors  bool      `toml:"disable_colors"`
	QuotaStatePath string    `toml:"quota_state_path"`
	UseMiddleProxy bool      `toml:"use_middle_proxy"`
	Modes          fileModes `toml:"modes"`
}

type fileModes struct {
	Classic bool `toml:"classic"`
	Secure  bool `toml:"secure"`
	TLS     bool `toml:"tls"`
}

type fileServer struct {
	Port             int            `toml:"port"`
	MetricsListen    string         `toml:"metrics_listen"`
	MetricsWhitelist []string       `toml:"metrics_whitelist"`
	API              fileAPI        `toml:"api"`
	Listeners        []fileListener `toml:"listeners,omitempty"`
}

type fileAPI struct {
	Enabled    bool     `toml:"enabled"`
	Listen     string   `toml:"listen,omitempty"`
	Whitelist  []string `toml:"whitelist,omitempty"`
	AuthHeader string   `toml:"auth_header,omitempty"`
	ReadOnly   bool     `toml:"read_only,omitempty"`
}

type fileListener struct {
	IP string `toml:"ip"`
}

type fileCensorship struct {
	TLSDomain    string `toml:"tls_domain"`
	Mask         bool   `toml:"mask"`
	TLSEmulation bool   `toml:"tls_emulation"`
	TLSFrontDir  string `toml:"tls_front_dir"`
}

type fileAccess struct {
	Users            map[string]string        `toml:"users"`
	UserEnabled      map[string]bool          `toml:"user_enabled,omitempty"`
	UserMaxUniqueIPs map[string]int           `toml:"user_max_unique_ips,omitempty"`
	UserMaxTCPConns  map[string]int           `toml:"user_max_tcp_conns,omitempty"`
	UserExpirations  map[string]string        `toml:"user_expirations,omitempty"`
	UserRateLimits   map[string]fileRateLimit `toml:"user_rate_limits,omitempty"`
}

type fileRateLimit struct {
	UpBps   uint64 `toml:"up_bps"`
	DownBps uint64 `toml:"down_bps"`
}

type fileUpstream struct {
	Type     string `toml:"type"`
	Address  string `toml:"address"`
	Username string `toml:"username"`
	Password string `toml:"password"`
}

// BuildConfig renders the telemt TOML config for one inbound. Only Fake-TLS
// (ee) mode is enabled: it is the only mode that looks like ordinary HTTPS to
// a censor. The metrics endpoint and, when asked for, a read-only control API
// are bound to loopback. Clients are relayed straight to the Telegram data
// centres, or through the SOCKS5 upstream: the Middle-End relays telemt tries
// by default only matter for a sponsored-channel ad tag, which the panel does
// not offer, and where they are unreachable they just log warnings on every
// start. telemt refuses to start without users, so at least one is required.
func BuildConfig(s Settings, users []User) ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	if len(users) == 0 {
		return nil, errors.New("telemt needs at least one user")
	}

	access := fileAccess{
		Users:            make(map[string]string, len(users)),
		UserEnabled:      map[string]bool{},
		UserMaxUniqueIPs: map[string]int{},
		UserMaxTCPConns:  map[string]int{},
		UserExpirations:  map[string]string{},
		UserRateLimits:   map[string]fileRateLimit{},
	}
	for _, u := range users {
		if !userNamePattern.MatchString(u.Name) {
			return nil, fmt.Errorf("invalid user name %q", u.Name)
		}
		if !ValidSecret(u.Secret) {
			return nil, fmt.Errorf("invalid secret for user %q", u.Name)
		}
		if _, dup := access.Users[u.Name]; dup {
			return nil, fmt.Errorf("duplicate user name %q", u.Name)
		}
		access.Users[u.Name] = u.Secret
		if u.Disabled {
			access.UserEnabled[u.Name] = false
		}
		if u.MaxUniqueIPs > 0 {
			access.UserMaxUniqueIPs[u.Name] = u.MaxUniqueIPs
		}
		if u.MaxTCPConns > 0 {
			access.UserMaxTCPConns[u.Name] = u.MaxTCPConns
		}
		if !u.Expires.IsZero() {
			access.UserExpirations[u.Name] = u.Expires.UTC().Format(time.RFC3339)
		}
		if u.RateUpBps > 0 || u.RateDownBps > 0 {
			access.UserRateLimits[u.Name] = fileRateLimit{UpBps: u.RateUpBps, DownBps: u.RateDownBps}
		}
	}

	cfg := fileConfig{
		General: fileGeneral{
			LogLevel:       "normal",
			DisableColors:  true,
			QuotaStatePath: "telemt.limit.json",
			UseMiddleProxy: false,
			Modes:          fileModes{TLS: true},
		},
		Server: fileServer{
			Port:             s.Port,
			MetricsListen:    fmt.Sprintf("127.0.0.1:%d", s.MetricsPort),
			MetricsWhitelist: []string{"127.0.0.1/32"},
		},
		Censorship: fileCensorship{
			TLSDomain:    s.TLSDomain,
			Mask:         true,
			TLSEmulation: true,
			TLSFrontDir:  "tlsfront",
		},
		Access: access,
	}
	if s.Listen != "" {
		cfg.Server.Listeners = []fileListener{{IP: s.Listen}}
	}
	if s.APIPort != 0 {
		cfg.Server.API = fileAPI{
			Enabled:    true,
			Listen:     fmt.Sprintf("127.0.0.1:%d", s.APIPort),
			Whitelist:  []string{"127.0.0.1/32"},
			AuthHeader: s.APIToken,
			ReadOnly:   true,
		}
	}
	if u := s.Upstream; u != nil {
		cfg.Upstreams = []fileUpstream{{Type: "socks5", Address: u.Address, Username: u.Username, Password: u.Password}}
	}
	return toml.Marshal(cfg)
}

// restartKey captures the settings telemt cannot hot-reload: a change in any
// of them needs a process restart, while user changes only need a reload.
func (s Settings) restartKey() string {
	key := fmt.Sprintf("%s|%d|%s|%d|%d|%s", s.Listen, s.Port, s.TLSDomain, s.MetricsPort, s.APIPort, s.APIToken)
	if u := s.Upstream; u != nil {
		key += fmt.Sprintf("|%s|%s|%s", u.Address, u.Username, u.Password)
	}
	return key
}

// UserName maps a panel client email to a telemt user name. telemt only
// accepts [A-Za-z0-9_.-]{1,64}; other emails get a stable name derived from
// the email, so traffic can still be attributed back to it.
func UserName(email string) string {
	if userNamePattern.MatchString(email) {
		return email
	}
	var b strings.Builder
	for _, r := range email {
		if r < 128 && (r == '_' || r == '.' || r == '-' || r >= '0' && r <= '9' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	name := b.String()
	sum := fnv32(email)
	if len(name) > 55 {
		name = name[:55]
	}
	return fmt.Sprintf("%s-%08x", name, sum)
}

func fnv32(s string) uint32 {
	h := uint32(2166136261)
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return h
}
