package telemt

import (
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// TestRealTelemt runs the real telemt binary named by TELEMT_BIN with configs
// generated by BuildConfig, and checks that it serves Fake-TLS on the inbound
// port, reports per-user metrics on loopback, and picks up a new user without
// a restart. CI sets TELEMT_BIN to the release the fork bundles; elsewhere the
// test is skipped.
func TestRealTelemt(t *testing.T) {
	bin := getenvOrSkip(t, "TELEMT_BIN")
	dir := t.TempDir()
	mgr := newManager(bin, func(id int) string { return filepath.Join(dir, fmt.Sprintf("inbound-%d", id)) })
	var logs []string
	logsCh := make(chan string, 1024)
	mgr.OnLog = func(_ int, line string) {
		select {
		case logsCh <- line:
		default:
		}
	}
	t.Cleanup(mgr.StopAll)
	dump := func() string {
		for {
			select {
			case l := <-logsCh:
				logs = append(logs, l)
			default:
				return strings.Join(logs, "\n")
			}
		}
	}

	inst := Instance{
		InboundID: 1,
		Tag:       "inbound-18443",
		Port:      18443,
		TLSDomain: "www.google.com",
		Users:     []User{{Name: "alice", Secret: strings.Repeat("ab", 16), MaxUniqueIPs: 2}, {Name: "bob.pc", Secret: strings.Repeat("cd", 16)}},
		Emails:    map[string]string{"alice": "alice@mail", "bob.pc": "bob"},
	}
	if err := mgr.Sync([]Instance{inst}); err != nil {
		t.Fatal(err)
	}

	deadline := time.Now().Add(60 * time.Second)
	for time.Now().Before(deadline) {
		if !mgr.Running(1) {
			t.Fatalf("telemt exited: %s\n%s", mgr.LastError(1), dump())
		}
		conn, err := net.DialTimeout("tcp", "127.0.0.1:18443", time.Second)
		if err == nil {
			conn.Close()
			break
		}
		time.Sleep(500 * time.Millisecond)
	}

	mgr.mu.Lock()
	port := mgr.instances[1].metricsPort
	mgr.mu.Unlock()
	var metricsErr error
	for time.Now().Before(deadline) {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		_, metricsErr = FetchUserCounters(ctx, port)
		cancel()
		if metricsErr == nil {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	if metricsErr != nil {
		t.Fatalf("metrics endpoint never answered: %v\n%s", metricsErr, dump())
	}
	if traffic := mgr.CollectTraffic(context.Background()); len(traffic) != 1 || traffic[0].Tag != "inbound-18443" {
		t.Fatalf("CollectTraffic = %+v", traffic)
	}

	// A user added later is hot-reloaded without a restart. Startup output is
	// set aside first so only lines after the change count.
	t.Logf("telemt startup output:\n%s", dump())
	logs = nil
	mgr.mu.Lock()
	proc := mgr.instances[1].proc
	mgr.mu.Unlock()
	inst.Users = append(inst.Users, User{Name: "carol", Secret: strings.Repeat("ef", 16)})
	inst.Emails["carol"] = "carol"
	if err := mgr.Sync([]Instance{inst}); err != nil {
		t.Fatal(err)
	}
	reloaded := false
	for end := time.Now().Add(30 * time.Second); time.Now().Before(end); time.Sleep(500 * time.Millisecond) {
		for _, line := range strings.Split(dump(), "\n") {
			if strings.Contains(strings.ToLower(line), "reload") || strings.Contains(line, "carol") {
				reloaded = true
			}
		}
		if reloaded {
			break
		}
	}
	mgr.mu.Lock()
	sameProc := mgr.instances[1].proc == proc
	mgr.mu.Unlock()
	if !sameProc || !mgr.Running(1) {
		t.Fatalf("adding a user must not restart telemt\n%s", dump())
	}
	if !reloaded {
		t.Fatalf("telemt did not log a config reload after adding a user\n%s", dump())
	}
	t.Logf("telemt output:\n%s", dump())
}

func getenvOrSkip(t *testing.T, key string) string {
	t.Helper()
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		t.Skip(key + " not set")
	}
	return v
}
