package telemt

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// TestRealTelemt runs the real telemt binary named by TELEMT_BIN with a config
// generated by BuildConfig, and checks its control API sees the users. CI sets
// TELEMT_BIN to the release the fork bundles; elsewhere the test is skipped.
func TestRealTelemt(t *testing.T) {
	bin := os.Getenv("TELEMT_BIN")
	if bin == "" {
		t.Skip("TELEMT_BIN not set")
	}
	dir := t.TempDir()
	mgr := newManager(bin, filepath.Join(dir, "telemt.toml"), filepath.Join(dir, "work"))
	t.Cleanup(mgr.Stop)

	s := Settings{Port: 18443, TLSDomain: "www.google.com", PublicHost: "203.0.113.7", APIPort: 19091, APIToken: "integration-token"}
	users := []User{
		{Name: "alice", Secret: strings.Repeat("ab", 16), Enabled: true, QuotaBytes: 1 << 30, MaxUniqueIPs: 2,
			ExpiresAt: time.Now().Add(24 * time.Hour)},
		{Name: "bob.pc", Secret: strings.Repeat("cd", 16), Enabled: false},
	}
	if err := mgr.Apply(true, s, users); err != nil {
		t.Fatal(err)
	}

	client := NewAPIClient(s)
	byName := func() map[string]UserStats {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		list, err := client.Users(ctx)
		if err != nil {
			return nil
		}
		m := map[string]UserStats{}
		for _, u := range list {
			m[u.Username] = u
		}
		return m
	}

	var got map[string]UserStats
	deadline := time.Now().Add(60 * time.Second)
	for time.Now().Before(deadline) && len(got) != 2 {
		if !mgr.Running() {
			t.Fatalf("telemt exited: %+v\n%s", mgr.Status(), strings.Join(mgr.Logs(), "\n"))
		}
		got = byName()
		time.Sleep(500 * time.Millisecond)
	}
	if len(got) != 2 {
		t.Fatalf("telemt API never listed both users: %v\n%s", got, strings.Join(mgr.Logs(), "\n"))
	}
	wantLink := Link("203.0.113.7", 18443, users[0].Secret, "www.google.com")
	if links := got["alice"].Links.TLS; len(links) == 0 || links[0] != wantLink {
		t.Fatalf("alice links = %v, want %s", links, wantLink)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if info, err := client.SystemInfo(ctx); err != nil || info.Version == "" {
		t.Fatalf("system info: %+v, %v", info, err)
	}

	// A user added later is picked up by hot reload without a restart.
	users = append(users, User{Name: "carol", Secret: strings.Repeat("ef", 16), Enabled: true})
	startedAt := mgr.Status().StartedAt
	if err := mgr.Apply(true, s, users); err != nil {
		t.Fatal(err)
	}
	deadline = time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		if _, ok := byName()["carol"]; ok {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	if _, ok := byName()["carol"]; !ok {
		t.Fatalf("hot reload did not add carol\n%s", strings.Join(mgr.Logs(), "\n"))
	}
	if !mgr.Status().StartedAt.Equal(startedAt) {
		t.Fatal("adding a user restarted telemt")
	}
}
