package telemt

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// TestRealTelemt runs the real telemt binary named by TELEMT_BIN with configs
// generated by BuildConfig, and checks that it serves Fake-TLS on the inbound
// port, reports per-user metrics on loopback, and picks up a new user without
// a restart. CI sets TELEMT_BIN to the release the fork bundles; elsewhere the
// test is skipped.
func TestRealTelemt(t *testing.T) {
	bin := getenvOrSkip(t, "TELEMT_BIN")
	// The instances live behind a symlink, as they do when the panel's bin
	// folder is one: telemt must still accept the config.
	dir := filepath.Join(t.TempDir(), "bin")
	if err := os.Symlink(t.TempDir(), dir); err != nil {
		t.Fatal(err)
	}
	mgr := newManager(bin, func(id int) string { return filepath.Join(dir, fmt.Sprintf("inbound-%d", id)) })
	var logs []string
	logsCh := make(chan string, 1024)
	mgr.OnLog = func(_ int, line string) {
		select {
		case logsCh <- line:
		default:
		}
	}
	t.Cleanup(mgr.StopAll)
	dump := func() string {
		for {
			select {
			case l := <-logsCh:
				logs = append(logs, l)
			default:
				return strings.Join(logs, "\n")
			}
		}
	}

	inst := Instance{
		InboundID: 1,
		Tag:       "inbound-18443",
		Port:      18443,
		TLSDomain: "www.google.com",
		Users: []User{
			{Name: "alice", Secret: strings.Repeat("ab", 16), MaxUniqueIPs: 2, MaxTCPConns: 8, RateUpBps: 5_000_000, RateDownBps: 20_000_000, Expires: time.Now().Add(24 * time.Hour)},
			{Name: "bob.pc", Secret: strings.Repeat("cd", 16), RateUpBps: MaxRateBps},
			{Name: "dave", Secret: strings.Repeat("12", 16), Disabled: true},
		},
		Emails: map[string]string{"alice": "alice@mail", "bob.pc": "bob", "dave": "dave"},
	}
	if err := mgr.Sync([]Instance{inst}); err != nil {
		t.Fatal(err)
	}

	deadline := time.Now().Add(60 * time.Second)
	for time.Now().Before(deadline) {
		if !mgr.Running(1) {
			t.Fatalf("telemt exited: %s\n%s", mgr.LastError(1), dump())
		}
		conn, err := net.DialTimeout("tcp", "127.0.0.1:18443", time.Second)
		if err == nil {
			conn.Close()
			break
		}
		time.Sleep(500 * time.Millisecond)
	}

	mgr.mu.Lock()
	port := mgr.instances[1].metricsPort
	mgr.mu.Unlock()
	var metricsErr error
	for time.Now().Before(deadline) {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		_, metricsErr = FetchUserCounters(ctx, port)
		cancel()
		if metricsErr == nil {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	if metricsErr != nil {
		t.Fatalf("metrics endpoint never answered: %v\n%s", metricsErr, dump())
	}
	if traffic := mgr.CollectTraffic(context.Background()); len(traffic) != 1 || traffic[0].Tag != "inbound-18443" {
		t.Fatalf("CollectTraffic = %+v", traffic)
	}

	// The dashboard shows the version and the running process.
	if v := mgr.Version(); !regexp.MustCompile(`^\d+\.\d+\.\d+`).MatchString(v) {
		t.Fatalf("Version() = %q", v)
	}
	if info := mgr.Process(1); !info.Running || info.PID <= 0 || info.StartedAt.IsZero() {
		t.Fatalf("Process(1) = %+v", info)
	}

	// The control API answers the panel's token, refuses any other, and
	// cannot change anything.
	var apiErr error
	for time.Now().Before(deadline) {
		if _, apiErr = mgr.UserIPs(context.Background(), 1, "alice"); apiErr == nil {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	if apiErr != nil {
		t.Fatalf("control API never answered: %v\n%s", apiErr, dump())
	}
	mgr.mu.Lock()
	apiPort, apiToken := mgr.instances[1].apiPort, mgr.instances[1].apiToken
	mgr.mu.Unlock()
	if _, err := fetchUserIPs(context.Background(), apiPort, "wrong", "alice"); err == nil {
		t.Fatal("the control API must refuse a wrong token")
	}
	req, _ := http.NewRequest(http.MethodPost, fmt.Sprintf("http://127.0.0.1:%d/v1/users/alice/disable", apiPort), nil)
	req.Header.Set("Authorization", apiToken)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusForbidden {
		t.Fatalf("the control API must be read-only, got HTTP %d", resp.StatusCode)
	}

	// Clients go straight to the Telegram data centres, so telemt must not
	// try the Middle-End relays at all.
	startup := dump()
	if strings.Contains(startup, "middle_proxy") || strings.Contains(startup, "Middle Proxy") {
		t.Fatalf("telemt started the Middle-End transport:\n%s", startup)
	}

	// A user added later is hot-reloaded without a restart. Startup output is
	// set aside first so only lines after the change count.
	t.Logf("telemt startup output:\n%s", startup)
	logs = nil
	mgr.mu.Lock()
	proc := mgr.instances[1].proc
	mgr.mu.Unlock()
	inst.Users = append(inst.Users, User{Name: "carol", Secret: strings.Repeat("ef", 16)})
	inst.Emails["carol"] = "carol"
	if err := mgr.Sync([]Instance{inst}); err != nil {
		t.Fatal(err)
	}
	reloaded := false
	for end := time.Now().Add(30 * time.Second); time.Now().Before(end); time.Sleep(500 * time.Millisecond) {
		for _, line := range strings.Split(dump(), "\n") {
			if strings.Contains(strings.ToLower(line), "reload") || strings.Contains(line, "carol") {
				reloaded = true
			}
		}
		if reloaded {
			break
		}
	}
	mgr.mu.Lock()
	sameProc := mgr.instances[1].proc == proc
	mgr.mu.Unlock()
	if !sameProc || !mgr.Running(1) {
		t.Fatalf("adding a user must not restart telemt\n%s", dump())
	}
	if !reloaded {
		t.Fatalf("telemt did not log a config reload after adding a user\n%s", dump())
	}
	t.Logf("telemt output:\n%s", dump())

	// A WEB proxy accepts the config, keeps the Fake-TLS port open beside
	// it, and sends a request without valid credentials under its secret
	// path on to the decoy site.
	decoy := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "decoy-site %s", r.URL.Path)
	}))
	defer decoy.Close()
	webbed := Instance{
		InboundID: 3,
		Tag:       "inbound-18445",
		Port:      18445,
		TLSDomain: "www.google.com",
		Web: &WebInstance{
			Host: "proxy.example.com", BasePath: "c0ffee42", PublicIP: "203.0.113.10",
			DecoyPort: decoy.Listener.Addr().(*net.TCPAddr).Port,
		},
		Users: []User{
			{Name: "frank", Secret: strings.Repeat("56", 16)},
			{Name: "gina", Secret: strings.Repeat("78", 16), Disabled: true},
		},
		Emails: map[string]string{"frank": "frank", "gina": "gina"},
	}
	if err := mgr.Sync([]Instance{inst, webbed}); err != nil {
		t.Fatal(err)
	}
	logs = nil
	var webErr error
	for end := time.Now().Add(60 * time.Second); time.Now().Before(end); time.Sleep(500 * time.Millisecond) {
		if !mgr.Running(3) {
			t.Fatalf("telemt with a WEB proxy exited: %s\n%s", mgr.LastError(3), dump())
		}
		if webErr = checkWebDecoy(mgr); webErr == nil {
			break
		}
	}
	if webErr != nil {
		t.Fatalf("the WEB proxy never answered: %v\n%s", webErr, dump())
	}
	conn, err := net.DialTimeout("tcp", "127.0.0.1:18445", time.Second)
	if err != nil {
		t.Fatalf("the Fake-TLS port must stay open beside the WEB proxy: %v\n%s", err, dump())
	}
	conn.Close()
	t.Logf("telemt output with a WEB proxy:\n%s", dump())

	// Stopping from the dashboard is not a failure, and Start brings the
	// proxies back on the next sync.
	mgr.Stop()
	if mgr.Running(1) || mgr.Running(3) || mgr.LastError(1) != "" || mgr.LastError(3) != "" {
		t.Fatalf("Stop must stop telemt without an error: %q %q", mgr.LastError(1), mgr.LastError(3))
	}
	mgr.Start()
	if err := mgr.Sync([]Instance{inst, webbed}); err != nil {
		t.Fatal(err)
	}
	if !mgr.Running(1) || !mgr.Running(3) {
		t.Fatalf("telemt must run again after Start: %s\n%s", mgr.LastError(1), dump())
	}
}

// checkWebDecoy asks the WEB proxy at c0ffee42 for a page without
// credentials, as the panel would pass it on, and expects the decoy site.
func checkWebDecoy(mgr *Manager) error {
	port, ok := mgr.WebRoute("c0ffee42")
	if !ok {
		return errors.New("no route to the WEB proxy")
	}
	req, err := http.NewRequest(http.MethodGet, fmt.Sprintf("http://127.0.0.1:%d/c0ffee42/?bridge=bogus", port), nil)
	if err != nil {
		return err
	}
	req.Host = "proxy.example.com"
	req.Header.Set("X-Forwarded-For", "198.51.100.7")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK || !strings.HasPrefix(string(body), "decoy-site /c0ffee42/") {
		return fmt.Errorf("HTTP %d %q", resp.StatusCode, body)
	}
	return nil
}

func getenvOrSkip(t *testing.T, key string) string {
	t.Helper()
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		t.Skip(key + " not set")
	}
	return v
}
